module.exports = [
  // Domestic Packages
  {
    category: "domestic",
    subcategory: "chardham",
    name: "Chardham Yatra",
    duration: "12 Days / 11 Nights",
    price: "₹25,999",
    numericPrice: 25999,
    rating: 4.8,
    reviews: 156,
    image:
      "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Sacred journey to Yamunotri, Gangotri, Kedarnath, and Badrinath",
    highlights: ["Temple Darshan", "River Ganga", "Himalayan Views", "Spiritual Experience"],
    location: "Uttarakhand",
  },
  {
    category: "domestic",
    subcategory: "chardham",
    name: "Kedarnath Special",
    duration: "6 Days / 5 Nights",
    price: "₹15,999",
    numericPrice: 15999,
    rating: 4.9,
    reviews: 89,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Direct journey to the sacred Kedarnath temple",
    highlights: ["Kedarnath Temple", "Guptkashi", "Sonprayag", "Mountain Trek"],
    location: "Uttarakhand",
  },
  {
    category: "domestic",
    subcategory: "south",
    name: "Kerala Backwaters",
    duration: "7 Days / 6 Nights",
    price: "₹18,999",
    numericPrice: 18999,
    rating: 4.7,
    reviews: 203,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Experience the serene backwaters and lush greenery of God's Own Country",
    highlights: ["Houseboat Cruise", "Ayurveda", "Tea Gardens", "Beach Visit"],
    location: "Kerala",
  },
  {
    category: "domestic",
    subcategory: "south",
    name: "Tamil Nadu Heritage",
    duration: "8 Days / 7 Nights",
    price: "₹22,999",
    numericPrice: 22999,
    rating: 4.6,
    reviews: 134,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Explore ancient temples and rich cultural heritage",
    highlights: ["Temple Architecture", "Cultural Shows", "Local Cuisine", "Historical Sites"],
    location: "Tamil Nadu",
  },
  {
    category: "domestic",
    subcategory: "north",
    name: "Golden Triangle",
    duration: "6 Days / 5 Nights",
    price: "₹19,999",
    numericPrice: 19999,
    rating: 4.8,
    reviews: 267,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Delhi - Agra - Jaipur circuit with iconic monuments",
    highlights: ["Taj Mahal", "Red Fort", "Amber Palace", "City Palace"],
    location: "Delhi, Agra, Jaipur",
  },
  {
    category: "domestic",
    subcategory: "north",
    name: "Rajasthan Royal",
    duration: "10 Days / 9 Nights",
    price: "₹28,999",
    numericPrice: 28999,
    rating: 4.9,
    reviews: 178,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Royal experience across the land of kings",
    highlights: ["Palace Hotels", "Desert Safari", "Folk Music", "Royal Heritage"],
    location: "Rajasthan",
  },
  {
    category: "domestic",
    subcategory: "kashmir",
    name: "Kashmir Paradise",
    duration: "8 Days / 7 Nights",
    price: "₹32,999",
    numericPrice: 32999,
    rating: 4.9,
    reviews: 145,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Experience the beauty of Kashmir Valley",
    highlights: ["Dal Lake", "Gulmarg", "Pahalgam", "Shikara Ride"],
    location: "Jammu & Kashmir",
  },
  {
    category: "domestic",
    subcategory: "kashmir",
    name: "Ladakh Adventure",
    duration: "12 Days / 11 Nights",
    price: "₹45,999",
    numericPrice: 45999,
    rating: 4.7,
    reviews: 98,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "High altitude adventure in the land of high passes",
    highlights: ["Pangong Lake", "Khardungla Pass", "Monasteries", "Mountain Biking"],
    location: "Ladakh",
  },
  {
    category: "domestic",
    subcategory: "bengal",
    name: "Darjeeling Hills",
    duration: "6 Days / 5 Nights",
    price: "₹16,999",
    numericPrice: 16999,
    rating: 4.6,
    reviews: 167,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Tea gardens and mountain views of the Queen of Hills",
    highlights: ["Tea Gardens", "Tiger Hill", "Toy Train", "Mountain Views"],
    location: "West Bengal",
  },
  {
    category: "domestic",
    subcategory: "bengal",
    name: "Sundarbans Wildlife",
    duration: "4 Days / 3 Nights",
    price: "₹12,999",
    numericPrice: 12999,
    rating: 4.5,
    reviews: 89,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Explore the mangrove forests and wildlife",
    highlights: ["Boat Safari", "Wildlife Spotting", "Mangrove Forest", "Local Culture"],
    location: "West Bengal",
  },

  // International Packages
  {
    category: "international",
    subcategory: "dubai",
    name: "Dubai Extravaganza",
    duration: "6 Days / 5 Nights",
    price: "₹45,999",
    numericPrice: 45999,
    rating: 4.9,
    reviews: 234,
    image:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Experience the luxury and grandeur of Dubai with iconic landmarks",
    highlights: ["Burj Khalifa", "Desert Safari", "Palm Jumeirah", "Dubai Mall"],
    location: "Dubai, UAE",
    visa: "Visa on Arrival",
  },
  {
    category: "international",
    subcategory: "dubai",
    name: "Dubai & Abu Dhabi",
    duration: "8 Days / 7 Nights",
    price: "₹52,999",
    numericPrice: 52999,
    rating: 4.8,
    reviews: 167,
    image:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Explore both Dubai and Abu Dhabi for a complete UAE experience",
    highlights: ["Sheikh Zayed Mosque", "Ferrari World", "Yas Island", "City Tour"],
    location: "Dubai & Abu Dhabi, UAE",
    visa: "Visa on Arrival",
  },
  {
    category: "international",
    subcategory: "singapore",
    name: "Singapore Discovery",
    duration: "5 Days / 4 Nights",
    price: "₹38,999",
    numericPrice: 38999,
    rating: 4.7,
    reviews: 189,
    image:
      "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Discover the modern marvels and cultural heritage of Singapore",
    highlights: ["Marina Bay Sands", "Universal Studios", "Gardens by the Bay", "Sentosa Island"],
    location: "Singapore",
    visa: "eVisa Required",
  },
  {
    category: "international",
    subcategory: "singapore",
    name: "Singapore & Malaysia",
    duration: "8 Days / 7 Nights",
    price: "₹49,999",
    numericPrice: 49999,
    rating: 4.6,
    reviews: 145,
    image:
      "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Combine Singapore with Malaysia for an extended Southeast Asian adventure",
    highlights: ["Kuala Lumpur", "Petronas Towers", "Malacca", "Cameron Highlands"],
    location: "Singapore & Malaysia",
    visa: "eVisa Required",
  },
  {
    category: "international",
    subcategory: "vietnam",
    name: "Vietnam Highlights",
    duration: "7 Days / 6 Nights",
    price: "₹32,999",
    numericPrice: 32999,
    rating: 4.8,
    reviews: 178,
    image:
      "https://images.unsplash.com/photo-1528127269322-539801943592?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Explore the rich culture and stunning landscapes of Vietnam",
    highlights: ["Halong Bay", "Hanoi Old Quarter", "Ho Chi Minh City", "Mekong Delta"],
    location: "Vietnam",
    visa: "eVisa Required",
  },
  {
    category: "international",
    subcategory: "vietnam",
    name: "Vietnam & Cambodia",
    duration: "10 Days / 9 Nights",
    price: "₹42,999",
    numericPrice: 42999,
    rating: 4.9,
    reviews: 123,
    image:
      "https://images.unsplash.com/photo-1528127269322-539801943592?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Combine Vietnam with Cambodia for an unforgettable Southeast Asian journey",
    highlights: ["Angkor Wat", "Siem Reap", "Phnom Penh", "Cu Chi Tunnels"],
    location: "Vietnam & Cambodia",
    visa: "eVisa Required",
  },
  {
    category: "international",
    subcategory: "thailand",
    name: "Thailand Paradise",
    duration: "6 Days / 5 Nights",
    price: "₹28,999",
    numericPrice: 28999,
    rating: 4.7,
    reviews: 256,
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Experience the beauty and culture of Thailand",
    highlights: ["Bangkok Temples", "Pattaya Beach", "Phi Phi Islands", "Thai Massage"],
    location: "Thailand",
    visa: "Visa on Arrival",
  },
  {
    category: "international",
    subcategory: "thailand",
    name: "Thailand & Bali",
    duration: "12 Days / 11 Nights",
    price: "₹58,999",
    numericPrice: 58999,
    rating: 4.8,
    reviews: 98,
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Combine Thailand with Bali for an exotic island adventure",
    highlights: ["Bali Temples", "Ubud Rice Terraces", "Kuta Beach", "Elephant Sanctuary"],
    location: "Thailand & Bali",
    visa: "Visa on Arrival",
  },
  {
    category: "international",
    subcategory: "nepal",
    name: "Nepal Adventure",
    duration: "8 Days / 7 Nights",
    price: "₹22,999",
    numericPrice: 22999,
    rating: 4.6,
    reviews: 134,
    image:
      "https://images.unsplash.com/photo-1544735716-392fe248dcec?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Explore the Himalayan kingdom with its rich culture and adventure",
    highlights: ["Kathmandu Valley", "Pokhara", "Mount Everest View", "Trekking"],
    location: "Nepal",
    visa: "Visa on Arrival",
  },
  {
    category: "international",
    subcategory: "nepal",
    name: "Nepal & Bhutan",
    duration: "10 Days / 9 Nights",
    price: "₹35,999",
    numericPrice: 35999,
    rating: 4.7,
    reviews: 87,
    image:
      "https://images.unsplash.com/photo-1544735716-392fe248dcec?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Discover the mystical kingdoms of Nepal and Bhutan",
    highlights: ["Tiger's Nest", "Paro Valley", "Thimphu", "Buddhist Monasteries"],
    location: "Nepal & Bhutan",
    visa: "Visa Required",
  },
  {
    category: "international",
    subcategory: "andaman",
    name: "Andaman Islands",
    duration: "6 Days / 5 Nights",
    price: "₹24,999",
    numericPrice: 24999,
    rating: 4.8,
    reviews: 198,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Experience the pristine beaches and crystal clear waters of Andaman",
    highlights: ["Port Blair", "Havelock Island", "Cellular Jail", "Water Sports"],
    location: "Andaman & Nicobar Islands",
    visa: "No Visa Required",
  },
  {
    category: "international",
    subcategory: "andaman",
    name: "Andaman Luxury",
    duration: "8 Days / 7 Nights",
    price: "₹34,999",
    numericPrice: 34999,
    rating: 4.9,
    reviews: 112,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Luxury beach resort experience in the Andaman Islands",
    highlights: ["Luxury Resorts", "Private Beach", "Scuba Diving", "Island Hopping"],
    location: "Andaman & Nicobar Islands",
    visa: "No Visa Required",
  },
];
