const ExcelJS = require("exceljs");
const logger = require("./logger");

const generateExcel = async (enquiries) => {
  try {
    // Create workbook and worksheet
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Enquiries");

    // Set up headers
    worksheet.columns = [
      { header: "Enquiry ID", key: "id", width: 25 },
      { header: "Name", key: "name", width: 25 },
      { header: "Email", key: "email", width: 30 },
      { header: "Phone", key: "phone", width: 20 },
      { header: "Destination", key: "destination", width: 20 },
      { header: "Travel Date", key: "travelDate", width: 15 },
      { header: "Travelers", key: "travelers", width: 12 },
      { header: "Budget", key: "budget", width: 15 },
      { header: "Status", key: "status", width: 15 },
      { header: "Message", key: "message", width: 40 },
      { header: "Submitted Date", key: "createdAt", width: 20 },
      { header: "IP Address", key: "ipAddress", width: 15 },
    ];

    // Style the header row
    worksheet.getRow(1).font = { bold: true, color: { argb: "FFFFFF" } };
    worksheet.getRow(1).fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1E293B" },
    };

    // Add data rows
    enquiries.forEach((enquiry, index) => {
      const row = worksheet.addRow({
        id: enquiry._id.toString(),
        name: enquiry.name,
        email: enquiry.email,
        phone: enquiry.phone,
        destination: enquiry.destination || "Not specified",
        travelDate: enquiry.travelDate
          ? new Date(enquiry.travelDate).toLocaleDateString()
          : "Not specified",
        travelers: enquiry.travelers || "Not specified",
        budget: formatBudget(enquiry.budget),
        status: formatStatus(enquiry.status),
        message: enquiry.message || "No additional requirements",
        createdAt: enquiry.createdAt.toLocaleString(),
        ipAddress: enquiry.ipAddress || "Not available",
      });

      // Alternate row colors for better readability
      if (index % 2 === 0) {
        row.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "FFF8FAFC" },
        };
      }

      // Style status column
      const statusCell = row.getCell("status");
      statusCell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: getStatusColor(enquiry.status) },
      };
    });

    // Add summary sheet
    const summarySheet = workbook.addWorksheet("Summary");

    // Summary statistics
    const totalEnquiries = enquiries.length;
    const statusCounts = {};
    const destinationCounts = {};

    enquiries.forEach((enquiry) => {
      // Count by status
      statusCounts[enquiry.status] = (statusCounts[enquiry.status] || 0) + 1;

      // Count by destination
      const dest = enquiry.destination || "Not specified";
      destinationCounts[dest] = (destinationCounts[dest] || 0) + 1;
    });

    // Add summary data
    summarySheet.columns = [
      { header: "Metric", key: "metric", width: 25 },
      { header: "Value", key: "value", width: 20 },
    ];

    summarySheet.getRow(1).font = { bold: true, color: { argb: "FFFFFF" } };
    summarySheet.getRow(1).fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFF59E0B" },
    };

    summarySheet.addRow({ metric: "Total Enquiries", value: totalEnquiries });
    summarySheet.addRow({ metric: "", value: "" }); // Empty row

    // Status breakdown
    summarySheet.addRow({ metric: "Status Breakdown", value: "" });
    Object.entries(statusCounts).forEach(([status, count]) => {
      summarySheet.addRow({
        metric: `  ${formatStatus(status)}`,
        value: `${count} (${((count / totalEnquiries) * 100).toFixed(1)}%)`,
      });
    });

    summarySheet.addRow({ metric: "", value: "" }); // Empty row

    // Destination breakdown
    summarySheet.addRow({ metric: "Destination Breakdown", value: "" });
    Object.entries(destinationCounts).forEach(([destination, count]) => {
      summarySheet.addRow({
        metric: `  ${destination}`,
        value: `${count} (${((count / totalEnquiries) * 100).toFixed(1)}%)`,
      });
    });

    // Add company info
    summarySheet.addRow({ metric: "", value: "" }); // Empty row
    summarySheet.addRow({ metric: "Generated by", value: "Satyam Holidays" });
    summarySheet.addRow({ metric: "Generated on", value: new Date().toLocaleString() });
    summarySheet.addRow({ metric: "Contact", value: "satyamholidays19@gmail.com" });

    // Generate buffer
    const buffer = await workbook.xlsx.writeBuffer();
    return buffer;
  } catch (error) {
    logger.error("Excel generation error:", error);
    throw error;
  }
};

// Helper functions
const formatBudget = (budget) => {
  const budgetMap = {
    "under-20k": "Under ₹20,000",
    "20k-50k": "₹20,000 - ₹50,000",
    "50k-1l": "₹50,000 - ₹1,00,000",
    "above-1l": "Above ₹1,00,000",
  };
  return budgetMap[budget] || budget || "Not specified";
};

const formatStatus = (status) => {
  const statusMap = {
    pending: "Pending",
    contacted: "Contacted",
    confirmed: "Confirmed",
    cancelled: "Cancelled",
  };
  return statusMap[status] || status;
};

const getStatusColor = (status) => {
  const colorMap = {
    pending: "FFFFF3CD", // Light yellow
    contacted: "FFD1ECF1", // Light blue
    confirmed: "FFD4EDDA", // Light green
    cancelled: "FFF8D7DA", // Light red
  };
  return colorMap[status] || "FFFFFFFF"; // Default white
};

module.exports = generateExcel;
